import { BookingLink } from '@/components/booking-link';
import { activeServices, priceLabel, serviceCategories } from '@/lib/services';

export function PriceList() {
  return <section className="mx-auto max-w-[1320px] px-7 py-16 lg:px-10 lg:py-20" id="priser" aria-labelledby="prices-title">
    <div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-wide text-[#922727]">Priser</p><h2 id="prices-title" className="mt-4 text-3xl font-bold tracking-[-0.04em] text-[#25252a] sm:text-4xl">Tjänster &amp; priser</h2><span className="mt-5 block h-0.5 w-10 bg-[#922727]" aria-hidden="true" /><p className="mt-5 text-[15px] leading-6 text-stone-600">Hitta rätt behandling för din bil. Här ser du våra tjänster och aktuella priser.</p></div>
    <div className="mt-12 space-y-14">{serviceCategories.map((category) => {
      const categoryServices = activeServices.filter((service) => service.category === category.id);
      return <section key={category.id} aria-labelledby={`${category.id}-title`}><div className="border-b-2 border-[#25252a] pb-4"><h3 id={`${category.id}-title`} className="text-2xl font-bold tracking-[-0.03em] text-[#25252a]">{category.name}</h3><p className="mt-1 text-sm text-stone-600">{category.description}</p></div><div>{categoryServices.map((service) => <article className="grid gap-6 border-b border-stone-300 py-7 md:grid-cols-[minmax(0,1fr)_240px] md:items-end md:gap-12" key={service.id}><div><h4 className="text-lg font-bold text-[#25252a]">{service.name}</h4><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">{service.fullDescription}</p>{service.included.length > 0 ? <><h5 className="mt-4 text-xs font-semibold uppercase tracking-wide text-stone-500">Det här ingår</h5><ul className="mt-2 flex flex-wrap gap-x-5 gap-y-2 text-sm text-stone-600">{service.included.map((item) => <li key={item} className="before:mr-2 before:text-[#922727] before:content-['•']">{item}</li>)}</ul></> : null}{service.treatmentTime || service.guarantee ? <p className="mt-4 text-sm text-stone-600">{service.treatmentTime ? <span>Behandlingstid: {service.treatmentTime}</span> : null}{service.treatmentTime && service.guarantee ? <span className="px-2 text-stone-400">·</span> : null}{service.guarantee ? <span>Garanti: {service.guarantee}</span> : null}</p> : null}</div><div className="flex flex-col gap-3 md:items-end"><div className="md:text-right"><p className="text-2xl font-bold tracking-[-0.04em] text-[#25252a]">{priceLabel(service)}</p>{service.suvPrice ? <p className="mt-1 text-sm font-medium text-stone-600">{service.suvPrice}</p> : null}{service.priceNote ? <p className="mt-2 max-w-[240px] text-xs leading-5 text-stone-500 md:ml-auto">{service.priceNote}</p> : null}</div><BookingLink serviceId={service.id} className="inline-flex min-h-10 w-full items-center justify-center border border-[#25252a] px-5 text-sm font-bold text-[#25252a] transition hover:bg-[#25252a] hover:text-white md:w-auto">Boka</BookingLink></div></article>)}</div></section>;
    })}</div>
    <p className="mt-12 border-l-2 border-[#922727] bg-stone-100 px-5 py-4 text-sm font-medium text-[#25252a]">Vid extra smutsiga bilar kan extra avgift tillkomma.</p>
  </section>;
}
