import { BookingLink } from '@/components/booking-link';
import { activeServices, priceLabel, serviceCategories } from '@/lib/services';

export function PopularPrice() {
  const service = activeServices.find((item) => item.popular && item.price);
  if (!service) return null;

  return <section className="border-y border-stone-300 bg-white" aria-labelledby="aktuellt-pris"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-7 sm:grid-cols-[1fr_auto_auto] sm:items-center sm:gap-10 lg:px-8"><div><p className="font-mono text-[10px] font-medium uppercase tracking-[0.14em] text-[#c94738]">AKTUELLT PRIS</p><h2 id="aktuellt-pris" className="mt-2 text-xl font-extrabold tracking-[-0.05em]">{service.name}</h2><p className="mt-1 text-sm text-slate-500">{service.shortDescription}</p></div><p className="font-serif text-3xl text-slate-950">{priceLabel(service)}</p><BookingLink serviceId={service.id} className="inline-flex min-h-11 items-center justify-center bg-slate-900 px-5 text-sm font-bold text-white transition hover:bg-[#c94738]">Boka handtvätt</BookingLink></div></section>;
}

export function PriceList() {
  return <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-30" id="priser" aria-labelledby="prices-title"><div className="max-w-2xl"><p className="font-mono text-[10px] font-medium uppercase tracking-[0.14em] text-[#c94738]">PRISER</p><h2 id="prices-title" className="mt-5 text-4xl font-extrabold leading-[0.95] tracking-[-0.075em] sm:text-5xl">Tjänster &amp; <em className="font-serif font-medium">priser.</em></h2><p className="mt-6 max-w-xl leading-7 text-slate-500">Hitta rätt behandling för din bil. Här ser du våra tjänster och aktuella priser.</p></div><div className="mt-14 space-y-16">{serviceCategories.map((category) => { const categoryServices = activeServices.filter((service) => service.category === category.id); if (!categoryServices.length) return null; return <section key={category.id} aria-labelledby={`${category.id}-title`}><div className="border-b-2 border-slate-950 pb-4"><h3 id={`${category.id}-title`} className="text-2xl font-extrabold tracking-[-0.05em]">{category.name}</h3><p className="mt-1 text-sm text-slate-500">{category.description}</p></div><div>{categoryServices.map((service) => <article className="grid gap-6 border-b border-stone-300 py-8 md:grid-cols-[minmax(0,1fr)_230px] md:items-end md:gap-12" key={service.id}><div><h4 className="text-xl font-extrabold tracking-[-0.04em] text-slate-950">{service.name}</h4><p className="mt-2 max-w-2xl leading-6 text-slate-600">{service.fullDescription}</p><ul className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600">{service.included.map((item) => <li key={item} className="before:mr-2 before:text-[#c94738] before:content-['•']">{item}</li>)}</ul></div><div className="flex flex-col gap-3 md:items-end"><div className="md:text-right"><p className="font-serif text-3xl leading-none text-slate-950">{priceLabel(service)}</p>{service.priceNote ? <p className="mt-2 max-w-[230px] text-xs leading-5 text-slate-500 md:ml-auto">{service.priceNote}</p> : null}</div><BookingLink serviceId={service.id} className="inline-flex min-h-11 w-full items-center justify-center border border-slate-900 px-5 text-sm font-bold text-slate-900 transition hover:bg-slate-900 hover:text-white md:w-auto">Boka</BookingLink></div></article>)}</div></section>; })}</div></section>;
}
